[package]
name = "mongo-embedding"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.28"

reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json",
] }
thiserror = "2.0.8"

tokio = {version = "1.42.0", features = ["full"]}