[package]
name = "mongo-embedding"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.28"

tokio = {version = "1.32.0", features = ["full"]}