[package]
name = "csv-tutor"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
chrono = "0.4.40"
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }

tokio = { version = "1", features = ["macros"] }
aws-sdk-s3 = "1.78.0"
aws-config = "1.5.18"
bytes = "1.10.1"
