[package]
name = "async_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.6"
futures-util = "0.3.31"
futures-core = "0.3.31"
tokio = { version = "1", features = ["full"] }