[package]
name = "medical-smartapp"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_http = "0.14.0"
url = "2.5.4"
reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json"
] }
serde = { version = "1.0.215", features = ["derive"] }
rand = "0.9.0"
sha2 = "0.10.8"
base64 = "0.22.1"

tokio = { version = "1", features = ["macros"] }