[package]
name = "medical-smartapp"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
url = "2.5.4"
reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json"
] }
serde = { version = "1.0.215", features = ["derive"] }

tokio = { version = "1", features = ["macros"] }
