[package]
name = "csv-data"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
csv-async = "1.2"
tokio-util = { version = "0.7", features = ["compat"] }
futures-util = "0.3.31"