[package]
name = "base-html"
version = "0.1.0"
edition = "2021"

[dependencies]

lambda_runtime = "0.13.0"
aws_lambda_events = "0.16.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
askama = "0.12.1"
http = "1.2.0"
