[package]
name = "gemini-apollo11"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json"
] }
serde_json = "1.0"
base64 = "0.22.1"

tokio = { version = "1", features = ["macros"] }
