[package]
name = "dynamodb_app"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.52.0"
serde_json = "1.0.133"

tokio = { version = "1", features = ["macros"] }
