[package]
name = "geo-search"
version = "0.1.0"
edition = "2024"

[dependencies]
bson = "2.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.25"
env_logger = "0.11.6"
futures = "0.3"

mongodb = "3.2.3"
tokio = {version = "1.42.0", features = ["full"]}
