[package]
name = "json_from_web"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "full"] }
reqwest = "0.11"
serde_json = "1.0.133"
jsonl = "4.0.1"