[package]
name = "s3-table"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3tables = "1.9.0"
aws-sdk-athena = "1.62.0"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }

tokio = { version = "1", features = ["full"] }
rand = "0.9.0"
chrono = "0.4.39"
