[package]
name = "medical-data"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }

tokio = { version = "1", features = ["macros"] }
