[package]
name = "regexample"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json"
] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
