[package]
name = "s3-table-proj"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.14.0"
aws-sdk-s3tables = "1.9.0"
aws-config = { version = "1.5.16", features = ["behavior-version-latest"] }

tokio = { version = "1", features = ["macros"] }
