[package]
name = "journal-clap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
home = "0.5"
serde_json = "1.0.128"
