[package]
name = "scraper_example"
version = "0.1.0"
edition = "2021"

[dependencies]

scraper = "0.22.0"
reqwest = { version = "0.12.9", default-features = false, features = [
  "rustls-tls",
  "json",
] }
tokio = { version = "1.42.0", features = ["full"] }
