[package]
name = "http-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0"
chrono = "0.4.38"