[package]
name = "sam-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = { version = "0.15.1", default-features = false, features = ["eventbridge"] }
lambda_runtime = "0.13.0"
aws-config = { version = "1.1.5", features = ["behavior-version-latest"] }
aws-smithy-types = "1.3.0"
aws-sdk-s3 = "1.78.0"
aws-sdk-dsql = "1.11.0"
aws-sigv4 = "1"
serde = { version = "1.0", features = ["derive"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid"] }
url = "2.5"
uuid = { version = "1.11", features = ["v4"] }
rsa = "0.9.7"
rustls = "0.23.19"

tokio = { version = "1.36", features = ["full"] }
